// Array of jokes
const myjokes = [
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Parallel lines have so much in common. It is a shame they will never meet.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "I'm on a whiskey diet. I've lost three days already!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "Why don't scientists trust stairs? Because they're always up to something!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the math book look sad? Because it had too many problems.",
    "How do you organize a space party? You planet!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call a fake noodle? An impasta!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the math book sad? It had too many problems.",
    "What do you call a shoe made of a banana? A slipper!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did one toilet say to the other toilet? You look a bit flushed!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the coffee file a police report? It got mugged!",
    "How does a penguin build its house? Igloos it together!",
    "Why don't we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "Why was the broom late? It overswept!",
    "How do you make a tissue dance? Put a little boogey in it!",
    "What's orange and sounds like a parrot? A carrot!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What's a pirate's favorite letter? Arrrrrr!",
    "Why couldn't the leopard play hide and seek? Because he was always spotted!",
    "How do you organize a space party? You planet!",
    "What do you call a fly without wings? A walk!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the math book sad? It had too many problems.",
    "What do you call a shoe made of a banana? A slipper!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did one toilet say to the other toilet? You look a bit flushed!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the coffee file a police report? It got mugged!",
    "How does a penguin build its house? Igloos it together!",
    "Why don't we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "Why was the broom late? It overswept!",
    "How do you make a tissue dance? Put a little boogey in it!",
    "What's orange and sounds like a parrot? A carrot!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What's a pirate's favorite letter? Arrrrrr!",
    "Why couldn't the leopard play hide and seek? Because he was always spotted!",
    "How do you organize a space party? You planet!",
    "What do you call a fly without wings? A walk!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the math book sad? It had too many problems.",
    "What do you call a shoe made of a banana? A slipper!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did one toilet say to the other toilet? You look a bit flushed!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the coffee file a police report? It got mugged!",
    "How does a penguin build its house? Igloos it together!",
    "Why don't we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "Why was the broom late? It overswept!",
    "How do you make a tissue dance? Put a little boogey in it!",
    "What's orange and sounds like a parrot? A carrot!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? ",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "I'm on a whiskey diet. I've lost three days already!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "Why don't scientists trust stairs? Because they're always up to something!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the math book look sad? Because it had too many problems.",
    "How do you organize a space party? You planet!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a fake noodle? An impasta!",
    "What do you call a pile of cats? A meowtain!",
    "What's a pirate's favorite letter? Arrrrrr!",
    "Why couldn't the leopard play hide and seek? Because he was always spotted!",
    "How do you make a tissue dance? Put a little boogey in it!",
    "What's orange and sounds like a parrot? A carrot!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the coffee file a police report? It got mugged!",
    "How does a penguin build its house? Igloos it together!",
    "Why don't we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "Why was the broom late? It overswept!",
    "What do you call a shoe made of a banana? A slipper!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did one toilet say to the other toilet? You look a bit flushed!",
    "Why did the snowman call his dog Frost? Because Frost bites!",
    "What do you call a factory that makes okay products? A satisfactory!",
    "hy did the math book look sad? Because it had too many problems.",
    "How do you organize a space party? You planet!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a fake noodle? An impasta!",
    "What's a pirate's favorite letter? Arrrrrr!",
    "Why couldn't the leopard play hide and seek? Because he was always spotted!",
    "How do you make a tissue dance? Put a little boogey in it!",
    "What's orange and sounds like a parrot? A carrot!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the coffee file a police report? It got mugged!",
    "How does a penguin build its house? Igloos it together!"
];

// Get the joke element
const jokeElement = document.getElementById('joke');

// Generate a random index
const randomIndex = Math.floor(Math.random() * myjokes.length);

// Display the joke
jokeElement.innerHTML = myjokes[randomIndex];



